steps:
  # Step 1: Build the Docker image using the Dockerfile in the Cloud Source Repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/container-one/container-one-image:$SHORT_SHA', '.']
  
  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/container-one/container-one-image:$SHORT_SHA']

 # Step 3: Prepare the deployment file from template
  - name: 'ubuntu'
    args: ['bash', '-c', 'cp deployment/c1-deployment-template.yaml deployment/c1-deployment.yaml && sed -i "s/IMAGE_TAG_PLACEHOLDER/$SHORT_SHA/" deployment/c1-deployment.yaml']

  # Step 4: Update the deployment with the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/c1-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci-5409-k8s'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/container-one/container-one-image:$SHORT_SHA'