steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'app-config.yaml', '-f', 'app-pvc.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=csci-5409-k8s'