services:
  container-one:
    image: smit0086/csci-5409-a1-container-one:latest
    ports:
      - 6000:6000
    env_file:
      - ./ContainerOne/.env
  
  container-two:
    image: smit0086/csci-5409-a1-container-two:latest
    ports:
      - 3001:3001
    volumes:
      - .:/app/files
    env_file:
      - ./ContainerTwo/.env